from .supervised import FreeRecallSumMSELoss ,FreeRecallSumMSEReciprocalVarLoss, FreeRecallSumMSEMultipleOutputLoss, \
    FreeRecallSumMSETrainEncodeLoss, FreeRecallSumMSETrainEncodeTwoDecisionLoss, FreeRecallSumCETrainEncodeLoss
from .rl import A2CLoss